import { DURACAO_RESERVA_HORAS, STATUS_RESERVA, type StatusReserva } from "./constants";
import type { Reserva, ResultadoValidacaoReserva } from "./types";
import { LIMITE_DETALHES_MOTIVO_CANCELAMENTO, MOTIVOS_CANCELAMENTO_RESERVA, type MotivoCancelamentoReserva } from "./constants";
export function calcularExpiracaoReserva(reservadoEm: string): string { return new Date(new Date(reservadoEm).getTime() + DURACAO_RESERVA_HORAS * 60 * 60 * 1000).toISOString(); }
export function possuiDuracaoOficialReserva(reserva: Pick<Reserva, "reservadoEm" | "expiraEm">): boolean { return new Date(reserva.expiraEm).getTime() - new Date(reserva.reservadoEm).getTime() === DURACAO_RESERVA_HORAS * 60 * 60 * 1000; }
export function validarCancelamentoReserva(status: StatusReserva): ResultadoValidacaoReserva { return status === STATUS_RESERVA.ATIVA ? { valido: true } : { valido: false, mensagem: "A reserva não pode ser cancelada." }; }
export function reservaEstaVencida(reserva: Pick<Reserva, "status" | "expiraEm">, agora: string): boolean { return reserva.status === STATUS_RESERVA.ATIVA && new Date(reserva.expiraEm).getTime() <= new Date(agora).getTime(); }
export function normalizarCancelamentoReserva(motivo:string,detalhes:string):{motivo:MotivoCancelamentoReserva|null;detalhes:string|null}{const m=Object.values(MOTIVOS_CANCELAMENTO_RESERVA).find(x=>x===motivo)??null;const d=detalhes.trim()||null;return{motivo:m,detalhes:m===MOTIVOS_CANCELAMENTO_RESERVA.OUTRO?d:null};}
export function validarMotivoCancelamentoReserva(motivo:MotivoCancelamentoReserva|null,detalhes:string|null):ResultadoValidacaoReserva{if(!motivo)return{valido:false,mensagem:"Selecione o motivo do cancelamento."};if(motivo===MOTIVOS_CANCELAMENTO_RESERVA.OUTRO&&(!detalhes||!detalhes.trim()))return{valido:false,mensagem:"Informe a descrição do motivo."};if(detalhes&&detalhes.length>LIMITE_DETALHES_MOTIVO_CANCELAMENTO)return{valido:false,mensagem:`A descrição deve ter no máximo ${LIMITE_DETALHES_MOTIVO_CANCELAMENTO} caracteres.`};return{valido:true};}
