import { detectarCamposAlteradosNegociacao, STATUS_NEGOCIACAO, validarDadosAtualizacaoNegociacao, validarDadosCriacaoNegociacao, validarTransicaoStatusNegociacao, type DadosAtualizacaoNegociacao, type DadosCriacaoNegociacao, type FiltrosNegociacoes, type ListagemNegociacoes, type Negociacao, type OrigemNegociacao, type StatusNegociacao } from "@/core/negociacoes";
import { CODIGOS_PERMISSAO_ACESSO, type ContextoAcesso } from "@/core/acesso";
import { STATUS_VEICULO, type Veiculo } from "@/core/veiculos";
import { exigirPermissao } from "./acesso.service";
import { obterUsuarioAtualAutenticado, type UsuarioAutenticado } from "./auth.service";

export type DadosFormularioNegociacao = { veiculoId: string; interessadoNome: string; interessadoTelefone: string; origem: OrigemNegociacao; observacoes: string };
export type DadosFormularioAtualizacaoNegociacao = Omit<DadosFormularioNegociacao, "veiculoId">;
export type DependenciasNegociacoes = { listar: (f: FiltrosNegociacoes) => Promise<ListagemNegociacoes>; obter: (id: string) => Promise<Negociacao | null>; criar: (d: DadosCriacaoNegociacao) => Promise<Negociacao>; atualizar: (id: string, d: DadosAtualizacaoNegociacao) => Promise<Negociacao | null>; encerrar: Record<"convertida" | "perdida" | "cancelada", (id: string) => Promise<Negociacao | null>>; usuario: () => Promise<UsuarioAutenticado | null>; visualizar: () => Promise<ContextoAcesso>; criarAcesso: () => Promise<ContextoAcesso>; alterarAcesso: () => Promise<ContextoAcesso>; encerrarAcesso: () => Promise<ContextoAcesso>; obterVeiculo: (id: string) => Promise<Veiculo>; listarVeiculos: () => Promise<readonly Veiculo[]>; auditarCriacao: (n: Negociacao, v: Veiculo) => Promise<void>; auditarAlteracao: (n: Negociacao, v: Veiculo, c: readonly string[]) => Promise<void>; auditarEncerramento: (a: Negociacao, n: Negociacao, v: Veiculo) => Promise<void> };
async function repo() { return import("@/lib/negociacoes/negociacoes.repository"); }
const PADRAO: DependenciasNegociacoes = {
  listar: async (f) => (await repo()).listarNegociacoesPersistidas(f), obter: async (id) => (await repo()).obterNegociacaoPersistidaPorId(id), criar: async (d) => (await repo()).criarNegociacaoPersistida(d), atualizar: async (id, d) => (await repo()).atualizarNegociacaoPersistida(id, d),
  encerrar: { convertida: async (id) => (await repo()).marcarNegociacaoConvertidaPersistida(id), perdida: async (id) => (await repo()).marcarNegociacaoPerdidaPersistida(id), cancelada: async (id) => (await repo()).cancelarNegociacaoPersistida(id) },
  usuario: obterUsuarioAtualAutenticado, visualizar: () => exigirPermissao(CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_VISUALIZAR), criarAcesso: () => exigirPermissao(CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_CRIAR), alterarAcesso: () => exigirPermissao(CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_ALTERAR), encerrarAcesso: () => exigirPermissao(CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_ENCERRAR),
  obterVeiculo: async (id) => (await import("./veiculos.service")).obterVeiculoPorId(id), listarVeiculos: async () => (await (await import("./veiculos.service")).listarVeiculos()).dados,
  auditarCriacao: async (n, v) => (await import("./negociacoes.auditoria")).registrarAuditoriaCriacaoNegociacao(n, v), auditarAlteracao: async (n, v, c) => (await import("./negociacoes.auditoria")).registrarAuditoriaAlteracaoNegociacao(n, v, c), auditarEncerramento: async (a, n, v) => (await import("./negociacoes.auditoria")).registrarAuditoriaEncerramentoNegociacao(a, n, v),
};
function deps(c: Partial<DependenciasNegociacoes>) { return { ...PADRAO, ...c, encerrar: { ...PADRAO.encerrar, ...c.encerrar } }; }
function norm(d: DadosFormularioAtualizacaoNegociacao): DadosAtualizacaoNegociacao { return { interessadoNome: d.interessadoNome.trim(), interessadoTelefone: d.interessadoTelefone.trim(), origem: d.origem, observacoes: d.observacoes.trim() || null }; }
async function auth(d: DependenciasNegociacoes) { const usuario = await d.usuario(); if (!usuario) throw new Error("Acesso não autorizado."); return usuario; }
export async function listarNegociacoes(f: FiltrosNegociacoes = {}, c: Partial<DependenciasNegociacoes> = {}) { const d = deps(c); await d.visualizar(); try { return await d.listar(f); } catch { throw new Error("Não foi possível concluir a operação."); } }
export async function obterNegociacaoPorId(id: string, c: Partial<DependenciasNegociacoes> = {}) { const d = deps(c); await auth(d); await d.visualizar(); try { const n = await d.obter(id); if (!n) throw new Error(); return n; } catch { throw new Error("Negociação não encontrada."); } }
export async function listarVeiculosDisponiveisParaNegociacao(c: Partial<DependenciasNegociacoes> = {}) { const d = deps(c); await d.visualizar(); return (await d.listarVeiculos()).filter((v) => v.status === STATUS_VEICULO.DISPONIVEL && v.arquivadoEm === null); }
export async function listarVeiculosParaConsultaDeNegociacoes(c: Partial<DependenciasNegociacoes> = {}) { const d = deps(c); await d.visualizar(); return d.listarVeiculos(); }
export async function criarNegociacao(form: DadosFormularioNegociacao, c: Partial<DependenciasNegociacoes> = {}) { const d = deps(c), usuario = await auth(d), contexto = await d.criarAcesso(); if (!contexto.vinculo.unidadeId) throw new Error("Acesso não autorizado."); const veiculo = await d.obterVeiculo(form.veiculoId); if (veiculo.status !== STATUS_VEICULO.DISPONIVEL || veiculo.arquivadoEm !== null) throw new Error("Não foi possível concluir a operação."); const dados = { ...norm(form), veiculoId: form.veiculoId.trim(), empresaId: contexto.vinculo.empresaId, unidadeId: contexto.vinculo.unidadeId, criadoPorUsuarioId: usuario.id }; const validacao = validarDadosCriacaoNegociacao(dados); if (!validacao.valido) throw new Error(validacao.mensagem); try { const n = await d.criar(dados); await d.auditarCriacao(n, veiculo); return n; } catch { throw new Error("Não foi possível concluir a operação."); } }
export async function atualizarNegociacao(id: string, form: DadosFormularioAtualizacaoNegociacao, c: Partial<DependenciasNegociacoes> = {}) { const d = deps(c); await auth(d); await d.alterarAcesso(); const anterior = await obterNegociacaoPorId(id, d); if (anterior.status !== STATUS_NEGOCIACAO.EM_ANDAMENTO) throw new Error("Não foi possível concluir a operação."); const dados = norm(form), validacao = validarDadosAtualizacaoNegociacao(dados); if (!validacao.valido) throw new Error(validacao.mensagem); try { const n = await d.atualizar(id, dados); if (!n) throw new Error(); const v = await d.obterVeiculo(n.veiculoId); await d.auditarAlteracao(n, v, detectarCamposAlteradosNegociacao(anterior, dados)); return n; } catch { throw new Error("Não foi possível concluir a operação."); } }
async function encerrar(id: string, destino: Exclude<StatusNegociacao, "em_andamento">, c: Partial<DependenciasNegociacoes>) { const d = deps(c); await auth(d); await d.encerrarAcesso(); const anterior = await obterNegociacaoPorId(id, d), validacao = validarTransicaoStatusNegociacao(anterior.status, destino); if (!validacao.valido) throw new Error("Não foi possível concluir a operação."); try { const n = await d.encerrar[destino](id); if (!n) throw new Error(); const v = await d.obterVeiculo(n.veiculoId); await d.auditarEncerramento(anterior, n, v); return n; } catch { throw new Error("Não foi possível concluir a operação."); } }
export const marcarNegociacaoConvertida = (id: string, c: Partial<DependenciasNegociacoes> = {}) => encerrar(id, "convertida", c);
export const marcarNegociacaoPerdida = (id: string, c: Partial<DependenciasNegociacoes> = {}) => encerrar(id, "perdida", c);
export const cancelarNegociacao = (id: string, c: Partial<DependenciasNegociacoes> = {}) => encerrar(id, "cancelada", c);
