import assert from "node:assert/strict"; import { readFileSync } from "node:fs"; import { resolve } from "node:path"; import { test } from "node:test"; import type { ContextoAcesso } from "@/core/acesso"; import type { Negociacao } from "@/core/negociacoes"; import type { Veiculo } from "@/core/veiculos"; import { atualizarNegociacao,cancelarNegociacao,criarNegociacao,listarNegociacoes,marcarNegociacaoConvertida,marcarNegociacaoPerdida,type DependenciasNegociacoes } from "./negociacoes.service"; import { atualizarNegociacaoPersistida,cancelarNegociacaoPersistida,criarNegociacaoPersistida,listarNegociacoesPersistidas,marcarNegociacaoConvertidaPersistida,marcarNegociacaoPerdidaPersistida,obterNegociacaoPersistidaPorId } from "@/lib/negociacoes/negociacoes.repository";
const C:ContextoAcesso={vinculo:{id:"x",usuarioId:"u",empresaId:"e",unidadeId:"un",perfilId:"p",ativo:true,criadoEm:"c"},perfil:{id:"p",codigo:"administrador",nome:"A",descricao:null,ativo:true,criadoEm:"c"},permissoes:[]}; const V:Veiculo={id:"car",empresaId:"e",unidadeId:"un",oportunidadeId:"o",proprietarioNome:"P",placa:"ABC",renavam:null,chassi:null,marca:"M",modelo:"X",versao:null,anoFabricacao:2025,anoModelo:2026,cor:"P",quilometragem:1,codigoFipe:null,status:"disponivel",criadoEm:"c",atualizadoEm:"a",arquivadoEm:null}; const N:Negociacao={id:"n",empresaId:"e",unidadeId:"un",veiculoId:"car",interessadoNome:"Ana",interessadoTelefone:"999",origem:"whatsapp",observacoes:null,status:"em_andamento",criadoPorUsuarioId:"u",criadoEm:"c",atualizadoEm:"a",encerradoEm:null};
function deps(a:Partial<DependenciasNegociacoes>={}):Partial<DependenciasNegociacoes>{return{usuario:async()=>({id:"u",email:"a@b.com"}),visualizar:async()=>C,criarAcesso:async()=>C,alterarAcesso:async()=>C,encerrarAcesso:async()=>C,obter:async()=>N,obterVeiculo:async()=>V,listarVeiculos:async()=>[V],listar:async()=>({dados:[N],total:1,pagina:1,itensPorPagina:10}),criar:async d=>({...N,...d}),atualizar:async(_id,d)=>({...N,...d}),encerrar:{convertida:async()=>({...N,status:"convertida",encerradoEm:"fim"}),perdida:async()=>({...N,status:"perdida",encerradoEm:"fim"}),cancelada:async()=>({...N,status:"cancelada",encerradoEm:"fim"})},auditarCriacao:async()=>{},auditarAlteracao:async()=>{},auditarEncerramento:async()=>{},...a}}
test("lista autorizado e controla erro",async()=>{assert.equal((await listarNegociacoes({},deps())).total,1);await assert.rejects(listarNegociacoes({},deps({listar:async()=>{throw Error()}})),new Error("Não foi possível concluir a operação."))});
for(const perfil of ["administrador","consultor"] as const)test(`cria para ${perfil} com contexto e usuário`,async()=>{let recebido:Record<string,unknown>={};await criarNegociacao({veiculoId:" car ",interessadoNome:" Ana ",interessadoTelefone:" 999 ",origem:"whatsapp",observacoes:" "},deps({criarAcesso:async()=>({...C,perfil:{...C.perfil,codigo:perfil}}),criar:async d=>{recebido=d;return{...N,...d}}}));assert.equal(recebido.empresaId,"e");assert.equal(recebido.unidadeId,"un");assert.equal(recebido.criadoPorUsuarioId,"u");assert.equal(recebido.observacoes,null)});
for(const perfil of ["teste","financeiro"] as const)test(`${perfil} não cria`,async()=>{let chamou=false;await assert.rejects(criarNegociacao({veiculoId:"car",interessadoNome:"Ana",interessadoTelefone:"9",origem:"site",observacoes:""},deps({criarAcesso:async()=>{throw Error("Acesso não autorizado.")},criar:async()=>{chamou=true;return N}})));assert.equal(chamou,false)});
test("veículo não disponível ou arquivado impede criação",async()=>{for(const v of [{...V,status:"em_preparacao" as const},{...V,arquivadoEm:"fim"}])await assert.rejects(criarNegociacao({veiculoId:"car",interessadoNome:"Ana",interessadoTelefone:"9",origem:"site",observacoes:""},deps({obterVeiculo:async()=>v})),new Error("Não foi possível concluir a operação."))});
test("entrada inválida não chama repository",async()=>{let chamou=false;await assert.rejects(criarNegociacao({veiculoId:"car",interessadoNome:" ",interessadoTelefone:"9",origem:"site",observacoes:""},deps({criar:async()=>{chamou=true;return N}})),new Error("Informe o interessado."));assert.equal(chamou,false)});
test("atualiza somente campos permitidos e audita depois",async()=>{const ordem:string[]=[];const n=await atualizarNegociacao("n",{interessadoNome:" Ana Maria ",interessadoTelefone:" 888 ",origem:"site",observacoes:" "},deps({atualizar:async(_id,d)=>{ordem.push("persistência");return{...N,...d}},auditarAlteracao:async()=>{ordem.push("auditoria")}}));assert.equal(n.interessadoNome,"Ana Maria");assert.equal(n.observacoes,null);assert.deepEqual(ordem,["persistência","auditoria"])});
test("listagem negada não consulta repository",async()=>{let chamou=false;await assert.rejects(listarNegociacoes({},deps({visualizar:async()=>{throw Error("Acesso não autorizado.")},listar:async()=>{chamou=true;throw Error()}})),new Error("Acesso não autorizado."));assert.equal(chamou,false)});
for(const [nome,fn,status] of [["convertida",marcarNegociacaoConvertida,"convertida"],["perdida",marcarNegociacaoPerdida,"perdida"],["cancelada",cancelarNegociacao,"cancelada"]] as const)test(`encerra como ${nome} e audita após persistência`,async()=>{const ordem:string[]=[];const operacao=async()=>{ordem.push("persistência");return{...N,status,encerradoEm:"fim"}};const n=await fn("n",deps({encerrar:{convertida:status==="convertida"?operacao:async()=>N,perdida:status==="perdida"?operacao:async()=>N,cancelada:status==="cancelada"?operacao:async()=>N},auditarEncerramento:async()=>{ordem.push("auditoria")}}));assert.equal(n.status,status);assert.deepEqual(ordem,["persistência","auditoria"])});
test("não repete encerramento nem audita falha",async()=>{let auditou=false;await assert.rejects(marcarNegociacaoConvertida("n",deps({obter:async()=>({...N,status:"convertida",encerradoEm:"fim"}),auditarEncerramento:async()=>{auditou=true}})),new Error("Não foi possível concluir a operação."));assert.equal(auditou,false)});
test("RPCs recebem somente ID e propagam erro",async()=>{for(const fn of [marcarNegociacaoConvertidaPersistida,marcarNegociacaoPerdidaPersistida,cancelarNegociacaoPersistida]){const p:Record<string,string>[]=[];await fn("n",async x=>{p.push(x);return{data:null,error:null}});assert.deepEqual(p,[{p_negociacao_id:"n"}]);await assert.rejects(fn("n",async()=>({data:null,error:Error("rpc")})),new Error("rpc"))}});
const LINHA={id:"n",empresa_id:"e",unidade_id:"un",veiculo_id:"car",interessado_nome:"Ana",interessado_telefone:"999",origem:"whatsapp" as const,observacoes:null,status:"em_andamento" as const,criado_por_usuario_id:"u",criado_em:"c",atualizado_em:"a",encerrado_em:null};
test("repository lista com paginação e filtros e mapeia integralmente",async()=>{let filtros:unknown;const r=await listarNegociacoesPersistidas({pesquisa:" ABC ",status:"em_andamento",pagina:2,itensPorPagina:10},async f=>{filtros=f;return{data:[LINHA],error:null,count:11}});assert.deepEqual(filtros,{pesquisa:"ABC",status:"em_andamento",pagina:2,itensPorPagina:10});assert.deepEqual(r,{dados:[N],total:11,pagina:2,itensPorPagina:10})});
test("repository obtém, cria e atualiza somente campos autorizados",async()=>{assert.deepEqual(await obterNegociacaoPersistidaPorId("n",async()=>({data:LINHA,error:null})),N);let criado:Record<string,string|null>={};await criarNegociacaoPersistida({empresaId:"e",unidadeId:"un",veiculoId:"car",interessadoNome:"Ana",interessadoTelefone:"999",origem:"whatsapp",observacoes:null,criadoPorUsuarioId:"u"},async d=>{criado=d;return{data:LINHA,error:null}});assert.equal("status" in criado,false);let atualizado:Record<string,string|null>={};await atualizarNegociacaoPersistida("n",{interessadoNome:"B",interessadoTelefone:"8",origem:"site",observacoes:null},async(_id,d)=>{atualizado=d;return{data:{...LINHA,interessado_nome:"B",interessado_telefone:"8",origem:"site"},error:null}});for(const x of ["status","empresa_id","unidade_id","veiculo_id","criado_por_usuario_id","criado_em","encerrado_em"])assert.equal(x in atualizado,false)});
const SQL=readFileSync(resolve(process.cwd(),"supabase/migrations/20260812_create_negociacoes.sql"),"utf8");
test("migração protege modelo, múltiplas negociações e RLS",()=>{for(const x of ["create table public.negociacoes","negociacoes_encerramento_check","enable row level security","negociacoes_select_contexto","negociacoes_insert_contexto","negociacoes_update_contexto","v.status='disponivel'","v.arquivado_em is null"])assert.ok(SQL.includes(x));assert.doesNotMatch(SQL,/unique[^;]*veiculo_id/i);assert.doesNotMatch(SQL,/for delete|to anon/i)});
test("migração possui três RPCs específicas seguras",()=>{for(const nome of ["marcar_negociacao_convertida","marcar_negociacao_perdida","cancelar_negociacao"]){assert.match(SQL,new RegExp(`create function public.${nome}\\(p_negociacao_id uuid\\)[\\s\\S]*?language plpgsql`));}for(const x of ["security definer","set search_path=''","for update","negociacoes.encerrar","revoke update on public.negociacoes","grant update (interessado_nome"])assert.ok(SQL.toLowerCase().includes(x.toLowerCase()));assert.doesNotMatch(SQL,/p_status|p_empresa|p_unidade/)});
