import assert from"node:assert/strict";import{test}from"node:test";import{CODIGOS_PERMISSAO_ACESSO,type CodigoPerfilAcesso,type CodigoPermissaoAcesso,type ContextoAcesso}from"@/core/acesso";import type{Negociacao}from"@/core/negociacoes";import type{Reserva}from"@/core/reservas";import type{Veiculo}from"@/core/veiculos";import{cancelarReserva,criarReserva,listarReservas,obterListagemReservasParaTela,type DependenciasReservas}from"./reservas.service";
const C:ContextoAcesso={vinculo: {id:"x",usuarioId:"user",redeId: "rede-matriz", operacaoId: "operacao-matriz", areaOperacionalId: "area-patrocinio", escopoTipo: "unidade", empresaId:"empresa",unidadeId:"unidade",perfilId:"p",ativo:true,criadoEm:"c"},perfil:{id:"p",codigo:"administrador",nome:"Administrador",descricao:null,ativo:true,criadoEm:"c"},permissoes:[]};const N={id:"n",empresaId:"empresa",unidadeId:"unidade",veiculoId:"v",interessadoNome:"Ana",interessadoTelefone:"9",origem:"site",observacoes:null,status:"em_andamento",criadoPorUsuarioId:"user",criadoEm:"c",atualizadoEm:"a",encerradoEm:null}as Negociacao;const V={id:"v",empresaId:"empresa",unidadeId:"unidade",oportunidadeId:"o",proprietarioNome:"P",placa:"ABC1234",renavam:null,chassi:null,marca:"Volkswagen",modelo:"Polo",versao:null,anoFabricacao:2025,anoModelo:2025,cor:"Prata",quilometragem:1,codigoFipe:null,status:"disponivel",criadoEm:"c",atualizadoEm:"a",arquivadoEm:null}as Veiculo;const R:Reserva={id:"r",empresaId:"empresa",unidadeId:"unidade",negociacaoId:"n",veiculoId:"v",status:"ativa",criadoPorUsuarioId:"user",reservadoEm:"2026-08-13T12:00:00Z",expiraEm:"2026-08-14T12:00:00Z",atualizadoEm:"2026-08-13T12:00:00Z",encerradoEm:null,motivoCancelamento:null,motivoCancelamentoDetalhes:null};const CONTEXTO_CANCELAR:ContextoAcesso={...C,permissoes:[{id:"pc",codigo:CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR,nome:"Cancelar",descricao:null,criadoEm:"c"}]};
function d(x:Partial<DependenciasReservas>={}):Partial<DependenciasReservas>{return{obterUsuario:async()=>({id:"user",email:"u@inato.com"}),obterContextoAutenticado:async()=>({usuario:{id:"user",email:"u@inato.com"},contexto:CONTEXTO_CANCELAR}),obterContextoOperacional:async()=>({redeId:"rede-matriz",operacaoId:"operacao-matriz",areaOperacionalId:"area-patrocinio",empresaId:"empresa",unidadeId:"unidade"}),visualizar:async()=>C,criarAcesso:async()=>C,cancelarAcesso:async()=>C,expirar:async()=>{},listar:async()=>({dados:[R],total:1}),listarApresentacao:async()=>({dados:[RESERVA_TELA],total:1}),obterReserva:async()=>R,obterPlacaVeiculo:async()=>"ABC1234",criar:async()=>R,cancelar:async(_id,dados)=>({...R,status:"cancelada",encerradoEm:"fim",motivoCancelamento:dados.motivo,motivoCancelamentoDetalhes:dados.detalhes}),obterNegociacao:async()=>N,obterVeiculo:async()=>V,auditarCriacao:async()=>{},auditarCancelamento:async()=>{},auditarCancelamentoInterno:async()=>{},...x}}
const RESERVA_TELA={...R,interessadoNome:"Ana",veiculoResumo:{placa:"ABC1234",marca:"Volkswagen",modelo:"Polo",versao:null}};
function contextoPerfil(perfil:CodigoPerfilAcesso,codigos:readonly CodigoPermissaoAcesso[]):ContextoAcesso{return{...C,perfil:{...C.perfil,codigo:perfil},permissoes:codigos.map((codigo,indice)=>({id:`permissao-${indice}`,codigo,nome:codigo,descricao:null,criadoEm:"c"}))}}
function tela(contexto:ContextoAcesso|null,x:Partial<DependenciasReservas>={}):Partial<DependenciasReservas>{return d({obterUsuario:async()=>{throw Error("Auth direto não deve ser chamado")},obterContextoAutenticado:async()=>contexto?{usuario:{id:"user",email:"u@inato.com"},contexto}:null,listarApresentacao:async()=>({dados:[RESERVA_TELA],total:1}),...x})}
test("caso de uso resolve contexto uma vez, sem Auth direto, e expira antes de listar",async()=>{let contextos=0;const ordem:string[]=[];const dependencias=tela(contextoPerfil("administrador",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR,CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR]),{obterContextoAutenticado:async()=>{contextos++;return{usuario:{id:"user",email:"u@inato.com"},contexto:contextoPerfil("administrador",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR,CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR])}},expirar:async()=>{ordem.push("expirar")},listarApresentacao:async()=>{ordem.push("listar");return{dados:[RESERVA_TELA],total:1}}});const resultado=await obterListagemReservasParaTela(dependencias);assert.equal(contextos,1);assert.deepEqual(ordem,["expirar","listar"]);assert.deepEqual(resultado,{estado:"carregado",reservas:{dados:[RESERVA_TELA],total:1},podeCancelar:true})});
for(const [perfil,codigos,estado,podeCancelar]of[["administrador",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR,CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR],"carregado",true],["consultor",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR,CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR],"carregado",true],["teste",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR],"carregado",false],["financeiro",[],"acesso_negado",false]]as const)test(`tela preserva perfil ${perfil}`,async()=>{let consultou=0;const resultado=await obterListagemReservasParaTela(tela(contextoPerfil(perfil,codigos),{listarApresentacao:async()=>{consultou++;return{dados:[RESERVA_TELA],total:1}}}));assert.equal(resultado.estado,estado);assert.equal(consultou,estado==="carregado"?1:0);if(resultado.estado==="carregado")assert.equal(resultado.podeCancelar,podeCancelar)});
test("ausência de autenticação não executa expiração nem listagem",async()=>{let operacoes=0;const resultado=await obterListagemReservasParaTela(tela(null,{expirar:async()=>{operacoes++},listarApresentacao:async()=>{operacoes++;return{dados:[],total:0}}}));assert.deepEqual(resultado,{estado:"nao_autenticado"});assert.equal(operacoes,0)});
test("falha da expiração impede listagem inconsistente",async()=>{let listou=false;await assert.rejects(obterListagemReservasParaTela(tela(contextoPerfil("administrador",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR]),{expirar:async()=>{throw Error("falha expiração")},listarApresentacao:async()=>{listou=true;return{dados:[],total:0}}})),new Error("falha expiração"));assert.equal(listou,false)});
test("falha da listagem é propagada",async()=>assert.rejects(obterListagemReservasParaTela(tela(contextoPerfil("administrador",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR]),{listarApresentacao:async()=>{throw Error("falha listagem")}})),new Error("falha listagem")));
test("cargas simultâneas idênticas compartilham somente a Promise em andamento",async()=>{let liberar!:()=>void;const espera=new Promise<void>(resolve=>{liberar=resolve});let contextos=0,expiracoes=0;const dependencias=tela(contextoPerfil("administrador",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR]),{obterContextoAutenticado:async()=>{contextos++;return{usuario:{id:"user",email:"u@inato.com"},contexto:contextoPerfil("administrador",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR])}},expirar:async()=>{expiracoes++;await espera}});const primeira=obterListagemReservasParaTela(dependencias),segunda=obterListagemReservasParaTela(dependencias);liberar();await Promise.all([primeira,segunda]);assert.equal(contextos,1);assert.equal(expiracoes,1)});
test("Promise é removida após sucesso",async()=>{let contextos=0;const dependencias=tela(contextoPerfil("administrador",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR]),{obterContextoAutenticado:async()=>{contextos++;return{usuario:{id:"user",email:"u@inato.com"},contexto:contextoPerfil("administrador",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR])}}});await obterListagemReservasParaTela(dependencias);await obterListagemReservasParaTela(dependencias);assert.equal(contextos,2)});
test("Promise é removida após falha e permite nova tentativa",async()=>{let tentativas=0;const dependencias=tela(contextoPerfil("administrador",[CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR]),{expirar:async()=>{tentativas++;if(tentativas===1)throw Error("falha temporária")}});await assert.rejects(obterListagemReservasParaTela(dependencias));const resultado=await obterListagemReservasParaTela(dependencias);assert.equal(resultado.estado,"carregado");assert.equal(tentativas,2)});
test("listagem de apresentação usa somente a consulta enriquecida",async()=>{const modulo=await import("./reservas.service");let catalogos=0;const resultado=await modulo.listarReservasParaApresentacao(d({listarApresentacao:async()=>({dados:[{...R,interessadoNome:"Ana",veiculoResumo:{placa:"ABC1234",marca:"Volkswagen",modelo:"Polo",versao:null}}],total:1}),obterNegociacao:async()=>{catalogos++;return N},obterVeiculo:async()=>{catalogos++;return V}}));assert.equal(resultado.dados[0].interessadoNome,"Ana");assert.equal(resultado.dados[0].veiculoResumo?.modelo,"Polo");assert.equal(catalogos,0)});
test("lista após materializar expiração",async()=>{const ordem:string[]=[];await listarReservas(d({expirar:async()=>{ordem.push("expirar")},listar:async()=>{ordem.push("listar");return{dados:[R],total:1}}}));assert.deepEqual(ordem,["expirar","listar"])});test("não autenticado é bloqueado",async()=>assert.rejects(criarReserva("n",d({obterUsuario:async()=>null})),new Error("Acesso não autorizado.")));for(const perfil of["administrador","consultor"]as const)test(`${perfil} cria`,async()=>assert.equal((await criarReserva("n",d({criarAcesso:async()=>({...C,perfil:{...C.perfil,codigo:perfil}})}))).id,"r"));for(const perfil of["teste","financeiro"]as const)test(`${perfil} não cria`,async()=>assert.rejects(criarReserva("n",d({criarAcesso:async()=>{throw Error("Acesso não autorizado.")}}))));test("negociação encerrada não cria",async()=>assert.rejects(criarReserva("n",d({obterNegociacao:async()=>({...N,status:"convertida",encerradoEm:"fim"})})),new Error("A negociação não pode ser reservada.")));test("veículo indisponível não cria",async()=>assert.rejects(criarReserva("n",d({obterVeiculo:async()=>({...V,status:"reservado"})})),new Error("O veículo não pode ser reservado.")));
test("cancela com motivo válido, audita e lista após persistência",async()=>{const ordem:string[]=[];const r=await cancelarReserva("r","cliente_desistiu","ignorado",d({cancelar:async(_id,dados)=>{ordem.push("persistência");assert.deepEqual(dados,{motivo:"cliente_desistiu",detalhes:null});return{...R,status:"cancelada",encerradoEm:"fim",motivoCancelamento:dados.motivo,motivoCancelamentoDetalhes:null}},auditarCancelamentoInterno:async()=>{ordem.push("auditoria")},listarApresentacao:async()=>{ordem.push("listagem");return{dados:[RESERVA_TELA],total:1}}}));assert.equal(r.reserva.motivoCancelamento,"cliente_desistiu");assert.equal(r.reserva.encerradoEm,"fim");assert.deepEqual(ordem,["persistência","auditoria","listagem"])});
test("sem motivo não cancela",async()=>assert.rejects(cancelarReserva("r","","",d()),new Error("Selecione o motivo do cancelamento.")));
test("motivo inválido não cancela",async()=>assert.rejects(cancelarReserva("r","invalido","",d()),new Error("Selecione o motivo do cancelamento.")));
test("outro sem detalhes não cancela",async()=>assert.rejects(cancelarReserva("r","outro","",d()),new Error("Informe a descrição do motivo.")));
test("outro com espaços não cancela",async()=>assert.rejects(cancelarReserva("r","outro","   ",d()),new Error("Informe a descrição do motivo.")));
test("outro válido normaliza detalhes",async()=>{const r=await cancelarReserva("r","outro","  Motivo específico  ",d());assert.equal(r.reserva.motivoCancelamento,"outro");assert.equal(r.reserva.motivoCancelamentoDetalhes,"Motivo específico")});
for(const status of["expirada","cancelada"]as const)test(`não cancela reserva ${status}`,async()=>assert.rejects(cancelarReserva("r","cliente_desistiu","",d({obterReserva:async()=>({...R,status,encerradoEm:"fim"})})),new Error("A reserva não pode ser cancelada.")));
test("falha persistente não audita",async()=>{let auditou=false;await assert.rejects(cancelarReserva("r","cliente_desistiu","",d({cancelar:async()=>{throw Error()},auditarCancelamentoInterno:async()=>{auditou=true}})));assert.equal(auditou,false)});
for(const perfil of["administrador","consultor"]as const)test(`${perfil} cancela com contexto único`,async()=>{const contexto=contextoPerfil(perfil,[CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR]);assert.equal((await cancelarReserva("r","cliente_desistiu","",d({obterContextoAutenticado:async()=>({usuario:{id:"user",email:"u@inato.com"},contexto})}))).reserva.status,"cancelada")});
for(const perfil of["teste","financeiro"]as const)test(`${perfil} não cancela`,async()=>assert.rejects(cancelarReserva("r","cliente_desistiu","",d({obterContextoAutenticado:async()=>({usuario:{id:"user",email:"u@inato.com"},contexto:contextoPerfil(perfil,[])})})),new Error("Acesso não autorizado.")));
test("usuário sem vínculo não cancela",async()=>assert.rejects(cancelarReserva("r","cliente_desistiu","",d({obterContextoAutenticado:async()=>null})),new Error("Acesso não autorizado.")));
for(const campo of["empresa","unidade"]as const)test(`${campo} incorreta impede cancelamento antes da placa e RPC`,async()=>{let placa=false,rpc=false;const reserva={...R,[campo==="empresa"?"empresaId":"unidadeId"]:"outro"};await assert.rejects(cancelarReserva("r","cliente_desistiu","",d({obterReserva:async()=>reserva,obterPlacaVeiculo:async()=>{placa=true;return"ABC1234"},cancelar:async()=>{rpc=true;return R}})),new Error("A reserva não pode ser cancelada."));assert.equal(placa,false);assert.equal(rpc,false)});
test("detalhes acima do limite são rejeitados antes da expiração",async()=>{let expirou=false;await assert.rejects(cancelarReserva("r","outro","x".repeat(501),d({expirar:async()=>{expirou=true}})),new Error("A descrição deve ter no máximo 500 caracteres."));assert.equal(expirou,false)});
test("Reserva inexistente não consulta placa nem RPC",async()=>{let placa=false,rpc=false;await assert.rejects(cancelarReserva("r","cliente_desistiu","",d({obterReserva:async()=>null,obterPlacaVeiculo:async()=>{placa=true;return"ABC1234"},cancelar:async()=>{rpc=true;return R}})),new Error("A reserva não pode ser cancelada."));assert.equal(placa,false);assert.equal(rpc,false)});
test("cancelamento composto resolve contexto uma vez e devolve listagem autoritativa",async()=>{let contextos=0;const ordem:string[]=[];const autoridade={usuario:{id:"user",email:"u@inato.com"},contexto:CONTEXTO_CANCELAR};const expirada={...RESERVA_TELA,id:"expirada",status:"expirada" as const,encerradoEm:"fim"};const resultado=await cancelarReserva("r","cliente_desistiu","",d({obterUsuario:async()=>{throw Error("Auth direto")},visualizar:async()=>{throw Error("Contexto repetido")},cancelarAcesso:async()=>{throw Error("Contexto repetido")},obterContextoAutenticado:async()=>{contextos++;return autoridade},expirar:async()=>{ordem.push("expirar")},obterReserva:async id=>{ordem.push(`reserva:${id}`);return R},obterNegociacao:async()=>{throw Error("Negociação consultada")},obterVeiculo:async()=>{throw Error("Veículo completo consultado")},obterPlacaVeiculo:async id=>{ordem.push(`placa:${id}`);return"ABC1234"},cancelar:async id=>{ordem.push(`rpc:${id}`);return{...R,status:"cancelada",encerradoEm:"fim",motivoCancelamento:"cliente_desistiu"}},auditarCancelamentoInterno:async(_r,negociacaoId,placa,recebida)=>{ordem.push("auditoria");assert.equal(negociacaoId,R.negociacaoId);assert.equal(placa,"ABC1234");assert.equal(recebida,autoridade)},listarApresentacao:async()=>{ordem.push("listagem");return{dados:[expirada],total:1}}}));assert.equal(contextos,1);assert.deepEqual(ordem,["expirar","reserva:r","placa:v","rpc:r","auditoria","listagem"]);assert.deepEqual(resultado.reservas,{dados:[expirada],total:1})});
test("falha da Auditoria mantém o tratamento atual após a RPC",async()=>{let persistiu=false;await assert.rejects(cancelarReserva("r","cliente_desistiu","",d({cancelar:async()=>{persistiu=true;return{...R,status:"cancelada",encerradoEm:"fim",motivoCancelamento:"cliente_desistiu"}},auditarCancelamentoInterno:async()=>{throw Error("falha auditoria")}})),new Error("Não foi possível cancelar a reserva."));assert.equal(persistiu,true)});
test("falha da listagem final é tratada depois da Auditoria",async()=>{let auditou=false;await assert.rejects(cancelarReserva("r","cliente_desistiu","",d({auditarCancelamentoInterno:async()=>{auditou=true},listarApresentacao:async()=>{throw Error("falha listagem")}})),new Error("Não foi possível cancelar a reserva."));assert.equal(auditou,true)});
