import { CODIGOS_PERMISSAO_ACESSO, possuiPermissao, type ContextoAcesso } from "@/core/acesso";
import type { ContextoOperacionalAtivo } from "@/core/organizacao";
import { STATUS_NEGOCIACAO, type Negociacao } from "@/core/negociacoes";
import { normalizarCancelamentoReserva, validarCancelamentoReserva, validarMotivoCancelamentoReserva, type DadosCancelamentoReserva, type ListagemReservas, type ListagemReservasApresentacao, type Reserva } from "@/core/reservas";
import { STATUS_VEICULO, type Veiculo } from "@/core/veiculos";
import { exigirPermissao, obterContextoAcessoAutenticadoAtual, type ContextoAcessoAutenticado } from "./acesso.service";
import { obterUsuarioAtualAutenticado, type UsuarioAutenticado } from "./auth.service";

export type DependenciasReservas={obterUsuario:()=>Promise<UsuarioAutenticado|null>;obterContextoAutenticado:()=>Promise<ContextoAcessoAutenticado|null>;obterContextoOperacional:()=>Promise<ContextoOperacionalAtivo>;visualizar:()=>Promise<ContextoAcesso>;criarAcesso:()=>Promise<ContextoAcesso>;cancelarAcesso:()=>Promise<ContextoAcesso>;expirar:()=>Promise<void>;listar:(c:ContextoOperacionalAtivo)=>Promise<ListagemReservas>;listarApresentacao:(c:ContextoOperacionalAtivo)=>Promise<ListagemReservasApresentacao>;obterReserva:(id:string,c:ContextoOperacionalAtivo)=>Promise<Reserva|null>;obterPlacaVeiculo:(id:string)=>Promise<string|null>;criar:(id:string)=>Promise<Reserva>;cancelar:(id:string,dados:DadosCancelamentoReserva)=>Promise<Reserva>;obterNegociacao:(id:string)=>Promise<Negociacao>;obterVeiculo:(id:string)=>Promise<Veiculo>;auditarCriacao:(r:Reserva,n:Negociacao,v:Veiculo)=>Promise<void>;auditarCancelamento:(r:Reserva,n:Negociacao,v:Veiculo)=>Promise<void>;auditarCancelamentoInterno:(r:Reserva,negociacaoId:string,placa:string,autoridade:ContextoAcessoAutenticado)=>Promise<void>};
async function repo(){return import("@/lib/reservas/reservas.repository");}
async function negociacao(id:string){const {obterNegociacaoPorId}=await import("./negociacoes.service");return obterNegociacaoPorId(id);}
async function veiculo(id:string){const {obterVeiculoPorId}=await import("./veiculos.service");return obterVeiculoPorId(id);}
async function placaVeiculo(id:string){const{obterPlacaVeiculoPersistidaPorId}=await import("@/lib/veiculos/veiculos.repository");return obterPlacaVeiculoPersistidaPorId(id);}
async function auditarCriacao(r:Reserva,n:Negociacao,v:Veiculo){return (await import("./reservas.auditoria")).registrarAuditoriaCriacaoReserva(r,n,v);}
async function auditarCancelamento(r:Reserva,n:Negociacao,v:Veiculo){return (await import("./reservas.auditoria")).registrarAuditoriaCancelamentoReserva(r,n,v);}
async function auditarCancelamentoInterno(r:Reserva,negociacaoId:string,placa:string,autoridade:ContextoAcessoAutenticado){return (await import("./reservas.auditoria")).registrarAuditoriaCancelamentoReservaComAutoridadeInterna(r,negociacaoId,placa,autoridade);}
const PADRAO:DependenciasReservas={
  obterUsuario:obterUsuarioAtualAutenticado,obterContextoAutenticado:()=>obterContextoAcessoAutenticadoAtual(),obterContextoOperacional:async()=>(await import("./contexto-operacional.service")).exigirContextoOperacionalAtivoAtual(),
  visualizar:()=>exigirPermissao(CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR),criarAcesso:()=>exigirPermissao(CODIGOS_PERMISSAO_ACESSO.RESERVAS_CRIAR),cancelarAcesso:()=>exigirPermissao(CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR),
  expirar:async()=>{await(await repo()).expirarReservasVencidasPersistidas();},listar:async c=>(await repo()).listarReservasPersistidas(undefined,c),listarApresentacao:async c=>(await repo()).listarReservasComDadosRelacionadosPersistidas(undefined,c),obterReserva:async(id,c)=>(await repo()).obterReservaPersistidaPorId(id,undefined,c),obterPlacaVeiculo:placaVeiculo,criar:async id=>(await repo()).criarReservaPersistida(id),cancelar:async(id,dados)=>(await repo()).cancelarReservaPersistida(id,dados),obterNegociacao:negociacao,obterVeiculo:veiculo,auditarCriacao,auditarCancelamento,auditarCancelamentoInterno
};
const deps=(c:Partial<DependenciasReservas>):DependenciasReservas=>({...PADRAO,...c});
async function autenticar(d:DependenciasReservas){if(!await d.obterUsuario())throw new Error("Acesso não autorizado.");}
const pertence=(r:{empresaId:string;unidadeId:string},c:ContextoOperacionalAtivo)=>r.empresaId===c.empresaId&&r.unidadeId===c.unidadeId;

export type ResultadoTelaReservas={estado:"nao_autenticado"}|{estado:"acesso_negado"}|{estado:"carregado";reservas:ListagemReservasApresentacao;podeCancelar:boolean};
const cargasTelaEmAndamento=new WeakMap<object,Promise<ResultadoTelaReservas>>();
async function executarCarregamentoTela(d:DependenciasReservas):Promise<ResultadoTelaReservas>{const autenticado=await d.obterContextoAutenticado();if(!autenticado)return{estado:"nao_autenticado"};const acesso=autenticado.contexto;if(!possuiPermissao(acesso,CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR))return{estado:"acesso_negado"};const contexto=await d.obterContextoOperacional(),podeCancelar=possuiPermissao(acesso,CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR);await d.expirar();const reservas=await d.listarApresentacao(contexto);return{estado:"carregado",reservas,podeCancelar};}
export function obterListagemReservasParaTela(c:Partial<DependenciasReservas>={}):Promise<ResultadoTelaReservas>{const padrao=Object.keys(c).length===0,chave=padrao?PADRAO:c,d=padrao?PADRAO:deps(c),existente=cargasTelaEmAndamento.get(chave);if(existente)return existente;const atual=executarCarregamentoTela(d);cargasTelaEmAndamento.set(chave,atual);return atual.finally(()=>{if(cargasTelaEmAndamento.get(chave)===atual)cargasTelaEmAndamento.delete(chave)});}
export async function listarReservas(c:Partial<DependenciasReservas>={}):Promise<ListagemReservas>{const d=deps(c);await autenticar(d);await d.visualizar();const contexto=await d.obterContextoOperacional();try{await d.expirar();return await d.listar(contexto)}catch{throw new Error("Não foi possível carregar as reservas.")}}
export async function listarReservasParaApresentacao(c:Partial<DependenciasReservas>={}):Promise<ListagemReservasApresentacao>{const d=deps(c);await autenticar(d);await d.visualizar();const contexto=await d.obterContextoOperacional();try{await d.expirar();return await d.listarApresentacao(contexto)}catch{throw new Error("Não foi possível carregar as reservas.")}}
export async function criarReserva(negociacaoId:string,c:Partial<DependenciasReservas>={}):Promise<Reserva>{const d=deps(c);await autenticar(d);await d.criarAcesso();const contexto=await d.obterContextoOperacional();await d.expirar();const n=await d.obterNegociacao(negociacaoId);if(!pertence(n,contexto)||n.status!==STATUS_NEGOCIACAO.EM_ANDAMENTO)throw new Error("A negociação não pode ser reservada.");const v=await d.obterVeiculo(n.veiculoId);if(!pertence(v,contexto)||v.status!==STATUS_VEICULO.DISPONIVEL||v.arquivadoEm!==null)throw new Error("O veículo não pode ser reservado.");try{const r=await d.criar(negociacaoId);if(!pertence(r,contexto))throw new Error();await d.auditarCriacao(r,n,v);return r}catch(e){if(e instanceof Error&&e.message.startsWith("Não foi possível registrar"))throw e;throw new Error("Não foi possível reservar o veículo.")}}
export type ResultadoCancelamentoReserva={reserva:Reserva;reservas:ListagemReservasApresentacao};
export async function cancelarReserva(id:string,motivo:string,detalhes:string,c:Partial<DependenciasReservas>={}):Promise<ResultadoCancelamentoReserva>{const d=deps(c),autoridade=await d.obterContextoAutenticado();if(!autoridade||!possuiPermissao(autoridade.contexto,CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR))throw new Error("Acesso não autorizado.");const contexto=await d.obterContextoOperacional(),dados=normalizarCancelamentoReserva(motivo,detalhes),validacao=validarMotivoCancelamentoReserva(dados.motivo,dados.detalhes);if(!validacao.valido)throw new Error(validacao.mensagem);await d.expirar();const atual=await d.obterReserva(id,contexto);if(!atual||!validarCancelamentoReserva(atual.status).valido||!pertence(atual,contexto))throw new Error("A reserva não pode ser cancelada.");const placa=await d.obterPlacaVeiculo(atual.veiculoId);if(!placa)throw new Error("Veículo não encontrado.");try{const reserva=await d.cancelar(id,{motivo:dados.motivo!,detalhes:dados.detalhes});if(!pertence(reserva,contexto))throw new Error();await d.auditarCancelamentoInterno(reserva,atual.negociacaoId,placa,autoridade);const reservas=await d.listarApresentacao(contexto);return{reserva,reservas}}catch{throw new Error("Não foi possível cancelar a reserva.")}}
