import { CODIGOS_PERMISSAO_ACESSO, type ContextoAcesso } from "@/core/acesso";
import { STATUS_NEGOCIACAO, type Negociacao } from "@/core/negociacoes";
import { normalizarCancelamentoReserva, validarCancelamentoReserva, validarMotivoCancelamentoReserva, type DadosCancelamentoReserva, type ListagemReservas, type Reserva } from "@/core/reservas";
import { STATUS_VEICULO, type Veiculo } from "@/core/veiculos";
import { exigirPermissao } from "./acesso.service";
import { obterUsuarioAtualAutenticado, type UsuarioAutenticado } from "./auth.service";
export type DependenciasReservas={obterUsuario:()=>Promise<UsuarioAutenticado|null>;visualizar:()=>Promise<ContextoAcesso>;criarAcesso:()=>Promise<ContextoAcesso>;cancelarAcesso:()=>Promise<ContextoAcesso>;expirar:()=>Promise<void>;listar:()=>Promise<ListagemReservas>;criar:(id:string)=>Promise<Reserva>;cancelar:(id:string,dados:DadosCancelamentoReserva)=>Promise<Reserva>;obterNegociacao:(id:string)=>Promise<Negociacao>;obterVeiculo:(id:string)=>Promise<Veiculo>;auditarCriacao:(r:Reserva,n:Negociacao,v:Veiculo)=>Promise<void>;auditarCancelamento:(r:Reserva,n:Negociacao,v:Veiculo)=>Promise<void>};
async function repo(){return import("@/lib/reservas/reservas.repository");} async function negociacao(id:string){const {obterNegociacaoPorId}=await import("./negociacoes.service");return obterNegociacaoPorId(id);} async function veiculo(id:string){const {obterVeiculoPorId}=await import("./veiculos.service");return obterVeiculoPorId(id);} async function auditarCriacao(r:Reserva,n:Negociacao,v:Veiculo){const m=await import("./reservas.auditoria");return m.registrarAuditoriaCriacaoReserva(r,n,v);} async function auditarCancelamento(r:Reserva,n:Negociacao,v:Veiculo){const m=await import("./reservas.auditoria");return m.registrarAuditoriaCancelamentoReserva(r,n,v);}
const PADRAO:DependenciasReservas={obterUsuario:obterUsuarioAtualAutenticado,visualizar:()=>exigirPermissao(CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR),criarAcesso:()=>exigirPermissao(CODIGOS_PERMISSAO_ACESSO.RESERVAS_CRIAR),cancelarAcesso:()=>exigirPermissao(CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR),expirar:async()=>{await (await repo()).expirarReservasVencidasPersistidas();},listar:async()=>(await repo()).listarReservasPersistidas(),criar:async id=>(await repo()).criarReservaPersistida(id),cancelar:async(id,dados)=>(await repo()).cancelarReservaPersistida(id,dados),obterNegociacao:negociacao,obterVeiculo:veiculo,auditarCriacao,auditarCancelamento};
const deps=(c:Partial<DependenciasReservas>):DependenciasReservas=>({...PADRAO,...c}); async function autenticar(d:DependenciasReservas){if(!await d.obterUsuario())throw new Error("Acesso não autorizado.");}
export async function listarReservas(c:Partial<DependenciasReservas>={}):Promise<ListagemReservas>{const d=deps(c);await autenticar(d);await d.visualizar();try{await d.expirar();return await d.listar();}catch{throw new Error("Não foi possível carregar as reservas.");}}
export async function criarReserva(negociacaoId:string,c:Partial<DependenciasReservas>={}):Promise<Reserva>{const d=deps(c);await autenticar(d);await d.criarAcesso();await d.expirar();const n=await d.obterNegociacao(negociacaoId);if(n.status!==STATUS_NEGOCIACAO.EM_ANDAMENTO)throw new Error("A negociação não pode ser reservada.");const v=await d.obterVeiculo(n.veiculoId);if(v.status!==STATUS_VEICULO.DISPONIVEL||v.arquivadoEm!==null)throw new Error("O veículo não pode ser reservado.");try{const r=await d.criar(negociacaoId);await d.auditarCriacao(r,n,v);return r;}catch(e){if(e instanceof Error&&e.message.startsWith("Não foi possível registrar"))throw e;throw new Error("Não foi possível reservar o veículo.");}}
export async function cancelarReserva(id:string,motivo:string,detalhes:string,c:Partial<DependenciasReservas>={}):Promise<Reserva>{const d=deps(c);await autenticar(d);await d.cancelarAcesso();const dados=normalizarCancelamentoReserva(motivo,detalhes),validacao=validarMotivoCancelamentoReserva(dados.motivo,dados.detalhes);if(!validacao.valido)throw new Error(validacao.mensagem);await d.expirar();const atual=(await d.listar()).dados.find(r=>r.id===id);if(!atual||!validarCancelamentoReserva(atual.status).valido)throw new Error("A reserva não pode ser cancelada.");const [n,v]=await Promise.all([d.obterNegociacao(atual.negociacaoId),d.obterVeiculo(atual.veiculoId)]);try{const r=await d.cancelar(id,{motivo:dados.motivo!,detalhes:dados.detalhes});await d.auditarCancelamento(r,n,v);return r;}catch{throw new Error("Não foi possível cancelar a reserva.");}}
