export const CODIGOS_PERFIL_ACESSO = {
  ADMINISTRADOR: "administrador",
  CONSULTOR: "consultor",
  FINANCEIRO: "financeiro",
  TESTE: "teste",
} as const;
export type CodigoPerfilAcesso = (typeof CODIGOS_PERFIL_ACESSO)[keyof typeof CODIGOS_PERFIL_ACESSO];

export const CODIGOS_PERMISSAO_ACESSO = {
  OPORTUNIDADES_VISUALIZAR: "oportunidades.visualizar",
  OPORTUNIDADES_CRIAR: "oportunidades.criar",
  OPORTUNIDADES_ALTERAR: "oportunidades.alterar",
  OPORTUNIDADES_EXCLUIR: "oportunidades.excluir",
  AUDITORIA_VISUALIZAR: "auditoria.visualizar",
  VEICULOS_PREPARACAO_CONCLUIR: "veiculos.preparacao.concluir",
  VEICULOS_PUBLICACAO_CONCLUIR: "veiculos.publicacao.concluir",
  NEGOCIACOES_VISUALIZAR: "negociacoes.visualizar",
  NEGOCIACOES_CRIAR: "negociacoes.criar",
  NEGOCIACOES_ALTERAR: "negociacoes.alterar",
  NEGOCIACOES_ENCERRAR: "negociacoes.encerrar",
  RESERVAS_VISUALIZAR: "reservas.visualizar",
  RESERVAS_CRIAR: "reservas.criar",
  RESERVAS_CANCELAR: "reservas.cancelar",
} as const;
export type CodigoPermissaoAcesso = (typeof CODIGOS_PERMISSAO_ACESSO)[keyof typeof CODIGOS_PERMISSAO_ACESSO];

export const PERMISSOES_INICIAIS_POR_PERFIL = {
  [CODIGOS_PERFIL_ACESSO.ADMINISTRADOR]: [CODIGOS_PERMISSAO_ACESSO.OPORTUNIDADES_VISUALIZAR, CODIGOS_PERMISSAO_ACESSO.OPORTUNIDADES_CRIAR, CODIGOS_PERMISSAO_ACESSO.OPORTUNIDADES_ALTERAR, CODIGOS_PERMISSAO_ACESSO.OPORTUNIDADES_EXCLUIR, CODIGOS_PERMISSAO_ACESSO.AUDITORIA_VISUALIZAR, CODIGOS_PERMISSAO_ACESSO.VEICULOS_PREPARACAO_CONCLUIR, CODIGOS_PERMISSAO_ACESSO.VEICULOS_PUBLICACAO_CONCLUIR, CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_VISUALIZAR, CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_CRIAR, CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_ALTERAR, CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_ENCERRAR, CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR, CODIGOS_PERMISSAO_ACESSO.RESERVAS_CRIAR, CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR],
  [CODIGOS_PERFIL_ACESSO.CONSULTOR]: [CODIGOS_PERMISSAO_ACESSO.OPORTUNIDADES_VISUALIZAR, CODIGOS_PERMISSAO_ACESSO.OPORTUNIDADES_CRIAR, CODIGOS_PERMISSAO_ACESSO.OPORTUNIDADES_ALTERAR, CODIGOS_PERMISSAO_ACESSO.OPORTUNIDADES_EXCLUIR, CODIGOS_PERMISSAO_ACESSO.VEICULOS_PREPARACAO_CONCLUIR, CODIGOS_PERMISSAO_ACESSO.VEICULOS_PUBLICACAO_CONCLUIR, CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_VISUALIZAR, CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_CRIAR, CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_ALTERAR, CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_ENCERRAR, CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR, CODIGOS_PERMISSAO_ACESSO.RESERVAS_CRIAR, CODIGOS_PERMISSAO_ACESSO.RESERVAS_CANCELAR],
  [CODIGOS_PERFIL_ACESSO.FINANCEIRO]: [],
  [CODIGOS_PERFIL_ACESSO.TESTE]: [CODIGOS_PERMISSAO_ACESSO.OPORTUNIDADES_VISUALIZAR, CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_VISUALIZAR, CODIGOS_PERMISSAO_ACESSO.RESERVAS_VISUALIZAR],
} as const;
