"use client";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CODIGOS_PERMISSAO_ACESSO } from "@/core/acesso";
import type { Negociacao, StatusNegociacao } from "@/core/negociacoes";
import type { Veiculo } from "@/core/veiculos";
import { usuarioAtualPossuiPermissao } from "@/services/acesso.service";
import { obterSessaoAtualAutenticada } from "@/services/auth.service";
import { criarNegociacao, listarNegociacoes, listarVeiculosDisponiveisParaNegociacao, listarVeiculosParaConsultaDeNegociacoes, type DadosFormularioNegociacao } from "@/services/negociacoes.service";
import AcessoNegado from "@/components/auth/AcessoNegado";
import NegociacaoFormulario from "./NegociacaoFormulario"; import NegociacoesEstadoVazio from "./NegociacoesEstadoVazio"; import NegociacoesFiltros from "./NegociacoesFiltros"; import NegociacoesPaginacao from "./NegociacoesPaginacao"; import NegociacoesTabela from "./NegociacoesTabela";
export default function NegociacoesContainer() { const router=useRouter(); const [dados,setDados]=useState<readonly Negociacao[]>([]); const [veiculos,setVeiculos]=useState<readonly Veiculo[]>([]); const [veiculosDisponiveis,setVeiculosDisponiveis]=useState<readonly Veiculo[]>([]); const [total,setTotal]=useState(0); const [pagina,setPagina]=useState(1); const [pesquisa,setPesquisa]=useState(""); const [status,setStatus]=useState<StatusNegociacao|"todos">("todos"); const [podeCriar,setPodeCriar]=useState(false); const [form,setForm]=useState(false); const [negado,setNegado]=useState(false); const [carregando,setCarregando]=useState(true); const [erro,setErro]=useState(""); const [mensagem,setMensagem]=useState("");
 const carregar=useCallback(async()=>{ const [lista,vs,disponiveis]=await Promise.all([listarNegociacoes({pagina,itensPorPagina:10,pesquisa,status}),listarVeiculosParaConsultaDeNegociacoes(),listarVeiculosDisponiveisParaNegociacao()]); setDados(lista.dados);setTotal(lista.total);setVeiculos(vs);setVeiculosDisponiveis(disponiveis);},[pagina,pesquisa,status]);
 useEffect(()=>{let ativo=true;setCarregando(true);obterSessaoAtualAutenticada().then(async s=>{if(!s){router.replace("/login");return;}const [v,c]=await Promise.all([usuarioAtualPossuiPermissao(CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_VISUALIZAR),usuarioAtualPossuiPermissao(CODIGOS_PERMISSAO_ACESSO.NEGOCIACOES_CRIAR)]);if(!v){if(ativo)setNegado(true);return;}if(ativo)setPodeCriar(c);await carregar();}).catch(()=>ativo&&setErro("Não foi possível concluir a operação.")).finally(()=>ativo&&setCarregando(false));return()=>{ativo=false};},[carregar,router]);
 async function salvar(d: DadosFormularioNegociacao){await criarNegociacao(d);setForm(false);setMensagem("Negociação criada com sucesso.");await carregar();}
 if(negado)return <AcessoNegado/>; return <main className="min-h-screen bg-slate-100 text-slate-900"><div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><p className="text-sm text-slate-500">INATO Central</p><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold">Negociações</h1><p className="mt-2 text-sm text-slate-500">Tratativas comerciais de veículos disponíveis.</p></div>{podeCriar&&!form&&<button onClick={()=>{setForm(true);setMensagem("")}} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Nova negociação</button>}</div>{mensagem&&<p className="mt-5 bg-emerald-50 p-3 text-sm text-emerald-700">{mensagem}</p>}{form&&<NegociacaoFormulario veiculos={veiculosDisponiveis} onCancelar={()=>setForm(false)} onSalvar={d=>salvar(d as DadosFormularioNegociacao)}/>}<section className="mt-6 overflow-hidden rounded-2xl bg-white shadow-sm"><NegociacoesFiltros pesquisa={pesquisa} status={status} onPesquisa={v=>{setPesquisa(v);setPagina(1)}} onStatus={v=>{setStatus(v);setPagina(1)}}/>{carregando?<div className="p-10 text-center">Carregando negociações...</div>:erro?<div className="p-10 text-center text-red-600">{erro}</div>:dados.length===0?<NegociacoesEstadoVazio/>:<NegociacoesTabela negociacoes={dados} veiculos={veiculos}/>}<NegociacoesPaginacao pagina={pagina} total={total} itensPorPagina={10} onPagina={setPagina}/></section></div></main>; }
